platform :ios, '14.0'

target 'SurfiOSTrainee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SurfiOSTrainee
  pod 'SnapKit'
  pod 'PanModal'

end
